import {execFileSync} from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import {createSandbox,buildAppEnv,launchDesktop,writeMockProviderConfig,writeEnvFile} from './e2e/fixtures.ts';
import {test,expect} from '@playwright/test';
test('native GitHub toggle and Files grouping',async()=>{
 test.setTimeout(90000);
 const out=path.resolve('../..','pane-smoke');fs.mkdirSync(out,{recursive:true});
 const s=createSandbox('pane-fixture');const src=process.env.GITHERMES_SOURCE || '/home/donovanyohan/githermes-pane-toggle';
 fs.cpSync(src,path.join(s.hermesHome,'plugins/githermes'),{recursive:true,filter:p=>!p.includes('/.git')&&!p.includes('/node_modules')});
 fs.cpSync(path.join(src,'desktop'),path.join(s.hermesHome,'desktop-plugins/githermes'),{recursive:true});
 writeMockProviderConfig(s.hermesHome,'http://127.0.0.1:1',undefined,'plugins:\n  enabled: [githermes]');writeEnvFile(s.hermesHome);
 const home=path.join(s.root,'os-home'), gh=path.join(home,'.config/gh'),bin=path.join(s.root,'bin');
 for(const p of [home,gh,bin])fs.mkdirSync(p,{recursive:true});
 fs.copyFileSync(path.resolve('../..','fake-gh-inbox.py'),path.join(bin,'gh'));fs.chmodSync(path.join(bin,'gh'),0o700);
 fs.appendFileSync(path.join(s.hermesHome,'.env'),`GH_CONFIG_DIR=${gh}\n`);
 const env=buildAppEnv(s,{HOME:home,XDG_CONFIG_HOME:path.join(home,'.config'),XDG_CACHE_HOME:path.join(home,'.cache'),PYTHONDONTWRITEBYTECODE:'1',TEST_WORKER_INDEX:'0',TERMINAL_HOME_MODE:'profile',HERMES_REAL_HOME:home,GH_CONFIG_DIR:gh,SHELL:'/bin/false',PATH:bin+':'+process.env.PATH});
 for(const k of ['HERMES_DESKTOP_DEV_SERVER','HERMES_DESKTOP_HERMES','HERMES_PROFILE','GH_DEBUG','GH_HOST'])delete env[k];
 const projectDir=path.join(s.root,'pane-project');fs.mkdirSync(projectDir);
 const seed='import sys; from hermes_state import SessionDB; db=SessionDB(); db.create_session("pane-fixture",source="desktop",cwd=sys.argv[1]); db.append_message("pane-fixture","user","Pane fixture session"); db.append_message("pane-fixture","assistant","Synthetic fixture only"); db.close()';
 execFileSync(path.resolve('../..','.venv/bin/python'),['-c',seed,projectDir],{cwd:path.resolve('../..'),env:{...env,HERMES_HOME:s.hermesHome}});
 let app,page;const errors=[];
 try{
  ({app,page}=await launchDesktop(env));page.on('pageerror',e=>errors.push(e.stack));
  await page.waitForTimeout(14000);
  await page.getByText('Pane fixture session',{exact:true}).first().click();
  await page.waitForTimeout(500);
  const icon=page.locator('button').filter({has:page.locator('.codicon-github')}).first();
  const pane=page.locator('[data-pane-id="githermes:pane"]');
  await icon.click();await page.waitForTimeout(1000);
  fs.writeFileSync(path.join(out,'opened.html'),await page.content());
  await page.screenshot({path:path.join(out,'opened.png')});
  await expect(page.getByRole('combobox',{name:'GitHub account'})).toBeVisible();
  await icon.click();
  await expect(page.getByRole('combobox',{name:'GitHub account'})).toBeHidden();
  await page.screenshot({path:path.join(out,'toggled-closed.png')});
  await expect(page.getByRole('button',{name:'GitHub',exact:true}).last()).toBeVisible();
  await icon.click();
  await expect(page.getByRole('combobox',{name:'GitHub account'})).toBeVisible();
  await page.getByRole('button',{name:'Show right sidebar',exact:true}).click();
  await page.waitForTimeout(600);
  const tab=page.locator('[data-tree-tab="githermes:pane"]');
  const files=page.locator('[data-tree-tab="files"]');
  await expect(tab).toBeVisible();await expect(files).toBeVisible();
  expect(await tab.evaluate(e=>e.closest('[data-tree-group]')?.getAttribute('data-tree-group'))).toBe(await files.evaluate(e=>e.closest('[data-tree-group]')?.getAttribute('data-tree-group')));
  await tab.click();await expect(page.getByRole('combobox',{name:'GitHub account'})).toBeVisible();
  await page.getByRole('button',{name:'Inbox',exact:true}).click();
  await expect(page.getByText('6 loaded',{exact:true})).toBeVisible();
  await page.screenshot({path:path.join(out,'files-github-tabs.png')});
  const groupOf=async loc=>loc.evaluate(e=>e.closest('[data-tree-group]')?.getAttribute('data-tree-group'));
  const drag=async(source,target,xFraction=.5,yFraction=.5)=>{
    const a=await source.boundingBox(),b=await target.boundingBox();expect(a).not.toBeNull();expect(b).not.toBeNull();
    await page.mouse.move(a!.x+12,a!.y+a!.height/2);await page.mouse.down();
    await page.mouse.move(a!.x+25,a!.y+a!.height/2+15,{steps:6});
    await page.mouse.move(b!.x+b!.width*xFraction,b!.y+b!.height*yFraction,{steps:20});
    await page.waitForTimeout(300);await page.mouse.up();await page.waitForTimeout(400);
  };
  await drag(tab,page.locator('[data-tree-group="grp-main"]').first(),.5,.15);
  await page.getByRole('combobox',{name:'GitHub account'}).hover();
  await page.keyboard.press('Control+Alt+t');
  await expect(tab).toBeVisible();
  await page.locator('[data-tree-group="grp-files"]').first().hover();
  await page.keyboard.press('Control+Alt+t');
  await expect(files).toBeVisible();
  expect(await groupOf(tab)).not.toBe(await groupOf(files));
  await page.screenshot({path:path.join(out,'dragged-out.png')});
  const detachedGroup=await groupOf(tab);
  await page.reload();await page.waitForTimeout(4000);
  await expect(tab).toBeVisible();
  expect(await groupOf(tab)).toBe(detachedGroup);
  expect(await groupOf(tab)).not.toBe(await groupOf(files));
  await page.screenshot({path:path.join(out,'persisted-detached.png')});
  await drag(tab,files);
  expect(await groupOf(tab)).toBe(await groupOf(files));
  await page.screenshot({path:path.join(out,'dragged-into-files.png')});
  await files.click();await expect(tab).toHaveAttribute('aria-selected','false');
  await icon.click();await expect(tab).toHaveAttribute('aria-selected','true');
  await icon.click();await expect(tab).toBeHidden();
  await icon.click();await expect(tab).toBeVisible();
  await tab.click({button:'right'});await page.getByRole('menuitem',{name:/^close$/i}).click();
  await expect(tab).toBeHidden();
  await page.getByRole('button',{name:'GitHub',exact:true}).last().click();
  await page.getByRole('button',{name:'Repository',exact:true}).first().click();
  await page.getByRole('button',{name:'Open pane',exact:true}).click();await expect(tab).toBeVisible();
  await page.getByRole('button',{name:'Open pane',exact:true}).click();await expect(tab).toBeVisible();
  for(let i=0;i<2;i++){
    await page.keyboard.press('Control+k');await page.getByRole('combobox').fill('Open GitHub pane');
    const open=page.getByRole('option',{name:/Open GitHub pane/});await expect(open).toBeVisible();
    await page.keyboard.press('ArrowDown');await expect(open).toHaveAttribute('aria-selected','true');
    await page.keyboard.press('Enter');await expect(tab).toBeVisible();
  }
  await page.screenshot({path:path.join(out,'open-idempotent.png')});
 }finally{
  if(page){fs.writeFileSync(path.join(out,'final.html'),await page.content());await page.screenshot({path:path.join(out,'final.png')});fs.writeFileSync(path.join(out,'storage.json'),JSON.stringify(await page.evaluate(()=>({...localStorage})),null,2));}
  fs.writeFileSync(path.join(out,'pageerrors.json'),JSON.stringify(errors,null,2));
  if(fs.existsSync(path.join(gh,'fixture-calls.jsonl')))fs.copyFileSync(path.join(gh,'fixture-calls.jsonl'),path.join(out,'fixture-calls.jsonl'));
  if(app)await app.close();
 }
});
